name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 安装 go
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.0"
          check-latest: true

      - name: Setup go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 编译
      - name: Build
        run: |
          go mod tidy
          go env -w GOARCH=amd64
          echo "编译 windows 版本"
          go env -w GOOS=windows
          go build -ldflags="-s -w" -o ./bin/rose.exe

      # 使用 upx 压缩可执行文件
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ./bin/*
          args: -fq

      - run: |
          cp wubi/data bin/data
          cp UnicodeCJK-WuBi/CJK.txt bin/data/
          cp pinyin-data/pinyin.txt bin/data/
          cp pinyin-data/duoyin.txt bin/data/
          cp pinyin-data/correct.txt bin/data/

          cp README.md bin/
          cp CHANGELOG.md bin/

      # 上传到 Artifact
      - name: Upload windows
        uses: actions/upload-artifact@v3
        with:
          name: rose
          path: ./bin/
